# Manual Bucket Configuration for C5Q

# This file allows manual override of the automatic bucket clustering
# Enable by setting buckets.manual_enabled: true in hparams.yaml

# Default k=6 buckets (data-driven from EDA)
k6_default:
  bucket_1: [12, 19, 32, 35, 37]
  bucket_2: [3, 6, 15, 17, 30, 39]
  bucket_3: [1, 4, 13, 16, 25, 27, 38]
  bucket_4: [14, 18, 23, 24, 33, 34]
  bucket_5: [5, 7, 9, 20, 28, 29, 31]
  bucket_6: [2, 8, 10, 11, 21, 22, 26, 36]

# Alternative k=5 configuration
k5_alternative:
  bucket_1: [1, 2, 3, 4, 5, 6, 7, 8]
  bucket_2: [9, 10, 11, 12, 13, 14, 15, 16]
  bucket_3: [17, 18, 19, 20, 21, 22, 23]
  bucket_4: [24, 25, 26, 27, 28, 29, 30, 31]
  bucket_5: [32, 33, 34, 35, 36, 37, 38, 39]

# Alternative k=4 configuration (quartiles)
k4_quartiles:
  bucket_1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  bucket_2: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  bucket_3: [21, 22, 23, 24, 25, 26, 27, 28, 29]
  bucket_4: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]

# Custom bucket configuration
# Users can define custom buckets here following the same format
custom:
  # Example custom configuration
  # bucket_1: [1, 5, 9, 13, 17, 21, 25, 29, 33, 37]  # Every 4th starting from 1
  # bucket_2: [2, 6, 10, 14, 18, 22, 26, 30, 34, 38] # Every 4th starting from 2
  # bucket_3: [3, 7, 11, 15, 19, 23, 27, 31, 35, 39] # Every 4th starting from 3
  # bucket_4: [4, 8, 12, 16, 20, 24, 28, 32, 36]     # Every 4th starting from 4

# Notes:
# - Each quantum state (1-39) must appear in exactly one bucket
# - Bucket sizes can be uneven
# - Buckets are used for model conditioning and bias terms
# - The bucket configuration affects model architecture and performance